service: wildbutton

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9850

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  wildbutton:
    handler: handler-serverless.handler
    events:
    - http:
        path: /
        method: get
    - http:
        path: /auth
        method: get
    - http:
        path: /commands
        method: post
    - http:
        path: /install
        method: get
    - http:
        path: /interactive
        method: post
  wildbutton-hourlycheck:
    handler: handler-serverless.hourly
    events:
    - schedule:
        rate: rate(1 minute)
        enabled: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
