service: wildbutton

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 10
  iamRoleStatements:
  - Effect: Allow
    Action:
    - lambda:InvokeFunction
    Resource:
    - arn:aws:lambda:${self:provider.region}:*:*

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9850

package:
  exclude:
    - node_modules/.cache/**
    - misc/**
    - __tests__/**
    - __mocks__/**
    - coverage/**

functions:
  wildbutton:
    handler: handler-serverless.combinedHandler
    events:
    - http:
        path: /
        method: get
    - http:
        path: /auth
        method: get
    - http:
        path: /commands
        method: post
    - http:
        path: /events
        method: post
    - http:
        path: /install
        method: get
    - http:
        path: /interactive
        method: post
    - schedule:
        rate: rate(10 minutes)
        enabled: true
    environment:
      ASYNC_HANDLER_LAMBDA: ${self:service}-${self:provider.stage}-wildbutton

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
