service: wildbutton

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 10
  iamRoleStatements:
  - Effect: Allow
    Action:
    - lambda:InvokeFunction
    Resource:
    - arn:aws:lambda:${self:provider.region}:*:*

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9850

package:
  exclude:
    - node_modules/.cache/**

functions:
  wildbutton:
    handler: handler-serverless.handler
    events:
    - http:
        path: /
        method: get
    - http:
        path: /auth
        method: get
    - http:
        path: /commands
        method: post
    - http:
        path: /install
        method: get
    - http:
        path: /interactive
        method: post
    environment:
      CLICK_RECORDER_LAMBDA: ${self:service}-${self:provider.stage}-wildbutton-click
  wildbutton-hourlycheck:
    handler: handler-serverless.hourly
    events:
    - schedule:
        rate: rate(1 hour)
        enabled: true
  wildbutton-click:
    handler: handler-serverless.click


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
