service: wildbutton

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
	iamRoleStatements:
	  - Effect: Allow
	    Action:
	      - lambda:InvokeFunction
	    Resource: "*"

custom:
  serverless-offline:
    host: 0.0.0.0
    httpPort: 9850

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  wildbutton:
    handler: handler-serverless.handler
    events:
    - http:
        path: /
        method: get
    - http:
        path: /auth
        method: get
    - http:
        path: /commands
        method: post
    - http:
        path: /install
        method: get
    - http:
        path: /interactive
        method: post
    environment:
      CLICK_RECORDER_LAMBDA: ${self:service}-${self:provider.stage}-wildbutton-click
  wildbutton-hourlycheck:
    handler: handler-serverless.hourly
    events:
    - schedule:
        rate: rate(1 hour)
        enabled: true
  wildbutton-click:
    handler: handler-serverless.click


plugins:
  - serverless-offline
  - serverless-dotenv-plugin
