# this is a self-reconfiguring pipeline, requires concourse >=5.8.0 :)
resources:
- name: wildbutton
  type: git
  source:
    uri: https://github.com/zozs/a-wild-button-appears
    branch: serverless-concourse
jobs:
- name: reconfigure
  plan:
  - get: wildbutton
    trigger: true
  - set_pipeline: wildbutton
    file: wildbutton/.concourse/pipeline.yml
- name: unittest
  plan:
  - get: wildbutton
    trigger: true
  - task: unittest
    file: wildbutton/.concourse/unittest_task.yml
